// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/v1/products.proto

package products

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_v1_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_api_v1_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *GetProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type IncreaseProductCountRequest struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Products      []*IncreaseProductCountRequest_IncreaseProductCountBatch `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseProductCountRequest) Reset() {
	*x = IncreaseProductCountRequest{}
	mi := &file_api_v1_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseProductCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseProductCountRequest) ProtoMessage() {}

func (x *IncreaseProductCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseProductCountRequest.ProtoReflect.Descriptor instead.
func (*IncreaseProductCountRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{2}
}

func (x *IncreaseProductCountRequest) GetProducts() []*IncreaseProductCountRequest_IncreaseProductCountBatch {
	if x != nil {
		return x.Products
	}
	return nil
}

type IncreaseProductCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseProductCountResponse) Reset() {
	*x = IncreaseProductCountResponse{}
	mi := &file_api_v1_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseProductCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseProductCountResponse) ProtoMessage() {}

func (x *IncreaseProductCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseProductCountResponse.ProtoReflect.Descriptor instead.
func (*IncreaseProductCountResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{3}
}

type ReserveProductRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Products      []*ReserveProductRequest_ProductCountBatch `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductRequest) Reset() {
	*x = ReserveProductRequest{}
	mi := &file_api_v1_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductRequest) ProtoMessage() {}

func (x *ReserveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveProductRequest) GetProducts() []*ReserveProductRequest_ProductCountBatch {
	if x != nil {
		return x.Products
	}
	return nil
}

type ReserveProductResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Results       []*ReserveProductResponse_ReservationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductResponse) Reset() {
	*x = ReserveProductResponse{}
	mi := &file_api_v1_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductResponse) ProtoMessage() {}

func (x *ReserveProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveProductResponse) GetResults() []*ReserveProductResponse_ReservationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReleaseReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationIds []int64                `protobuf:"varint,1,rep,packed,name=reservation_ids,json=reservationIds,proto3" json:"reservation_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_api_v1_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseReservationRequest) GetReservationIds() []int64 {
	if x != nil {
		return x.ReservationIds
	}
	return nil
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_api_v1_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{7}
}

type ConfirmReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationIds []int64                `protobuf:"varint,1,rep,packed,name=reservation_ids,json=reservationIds,proto3" json:"reservation_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_api_v1_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmReservationRequest) GetReservationIds() []int64 {
	if x != nil {
		return x.ReservationIds
	}
	return nil
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_api_v1_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{9}
}

type IncreaseProductCountRequest_IncreaseProductCountBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseProductCountRequest_IncreaseProductCountBatch) Reset() {
	*x = IncreaseProductCountRequest_IncreaseProductCountBatch{}
	mi := &file_api_v1_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseProductCountRequest_IncreaseProductCountBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseProductCountRequest_IncreaseProductCountBatch) ProtoMessage() {}

func (x *IncreaseProductCountRequest_IncreaseProductCountBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseProductCountRequest_IncreaseProductCountBatch.ProtoReflect.Descriptor instead.
func (*IncreaseProductCountRequest_IncreaseProductCountBatch) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{2, 0}
}

func (x *IncreaseProductCountRequest_IncreaseProductCountBatch) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *IncreaseProductCountRequest_IncreaseProductCountBatch) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReserveProductRequest_ProductCountBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductRequest_ProductCountBatch) Reset() {
	*x = ReserveProductRequest_ProductCountBatch{}
	mi := &file_api_v1_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductRequest_ProductCountBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductRequest_ProductCountBatch) ProtoMessage() {}

func (x *ReserveProductRequest_ProductCountBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductRequest_ProductCountBatch.ProtoReflect.Descriptor instead.
func (*ReserveProductRequest_ProductCountBatch) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ReserveProductRequest_ProductCountBatch) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *ReserveProductRequest_ProductCountBatch) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReserveProductResponse_ReservationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId int64                  `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Sku           uint64                 `protobuf:"varint,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductResponse_ReservationResult) Reset() {
	*x = ReserveProductResponse_ReservationResult{}
	mi := &file_api_v1_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductResponse_ReservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductResponse_ReservationResult) ProtoMessage() {}

func (x *ReserveProductResponse_ReservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductResponse_ReservationResult.ProtoReflect.Descriptor instead.
func (*ReserveProductResponse_ReservationResult) Descriptor() ([]byte, []int) {
	return file_api_v1_products_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ReserveProductResponse_ReservationResult) GetReservationId() int64 {
	if x != nil {
		return x.ReservationId
	}
	return 0
}

func (x *ReserveProductResponse_ReservationResult) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

var File_api_v1_products_proto protoreflect.FileDescriptor

const file_api_v1_products_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/products.proto\x12\bproducts\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"%\n" +
	"\x11GetProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\"f\n" +
	"\x12GetProductResponse\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"\xbf\x01\n" +
	"\x1bIncreaseProductCountRequest\x12[\n" +
	"\bproducts\x18\x01 \x03(\v2?.products.IncreaseProductCountRequest.IncreaseProductCountBatchR\bproducts\x1aC\n" +
	"\x19IncreaseProductCountBatch\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x1e\n" +
	"\x1cIncreaseProductCountResponse\"\xa3\x01\n" +
	"\x15ReserveProductRequest\x12M\n" +
	"\bproducts\x18\x01 \x03(\v21.products.ReserveProductRequest.ProductCountBatchR\bproducts\x1a;\n" +
	"\x11ProductCountBatch\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xb4\x01\n" +
	"\x16ReserveProductResponse\x12L\n" +
	"\aresults\x18\x01 \x03(\v22.products.ReserveProductResponse.ReservationResultR\aresults\x1aL\n" +
	"\x11ReservationResult\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\x03R\rreservationId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\x04R\x03sku\"D\n" +
	"\x19ReleaseReservationRequest\x12'\n" +
	"\x0freservation_ids\x18\x01 \x03(\x03R\x0ereservationIds\"\x1c\n" +
	"\x1aReleaseReservationResponse\"D\n" +
	"\x19ConfirmReservationRequest\x12'\n" +
	"\x0freservation_ids\x18\x01 \x03(\x03R\x0ereservationIds\"\x1c\n" +
	"\x1aConfirmReservationResponse2\xd4\x05\n" +
	"\bProducts\x12\xa3\x01\n" +
	"\n" +
	"GetProduct\x12\x1b.products.GetProductRequest\x1a\x1c.products.GetProductResponse\"Z\x92A=\x1a;Получение информации о продукте\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/products/{sku}\x12\x8d\x01\n" +
	"\x14IncreaseProductCount\x12%.products.IncreaseProductCountRequest\x1a&.products.IncreaseProductCountResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/products/increase-count\x12t\n" +
	"\x0eReserveProduct\x12\x1f.products.ReserveProductRequest\x1a .products.ReserveProductResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/products/reserve\x12\x8c\x01\n" +
	"\x12ReleaseReservation\x12#.products.ReleaseReservationRequest\x1a$.products.ReleaseReservationResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/products/release-reservation\x12\x8c\x01\n" +
	"\x12ConfirmReservation\x12#.products.ConfirmReservationRequest\x1a$.products.ConfirmReservationResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/products/confirm-reservationB\x9c\x01\x92Ag\x12\x15\n" +
	"\fProducts API2\x051.0.0*\x02\x01\x022\x10application/json:\x10application/jsonZ\x18\n" +
	"\x16\n" +
	"\x06x-auth\x12\f\b\x02\x1a\x06x-auth \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06x-auth\x12\x00Z0ozon-simulator-go-products/api/v1/proto;productsb\x06proto3"

var (
	file_api_v1_products_proto_rawDescOnce sync.Once
	file_api_v1_products_proto_rawDescData []byte
)

func file_api_v1_products_proto_rawDescGZIP() []byte {
	file_api_v1_products_proto_rawDescOnce.Do(func() {
		file_api_v1_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_products_proto_rawDesc), len(file_api_v1_products_proto_rawDesc)))
	})
	return file_api_v1_products_proto_rawDescData
}

var file_api_v1_products_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_products_proto_goTypes = []any{
	(*GetProductRequest)(nil),                                     // 0: products.GetProductRequest
	(*GetProductResponse)(nil),                                    // 1: products.GetProductResponse
	(*IncreaseProductCountRequest)(nil),                           // 2: products.IncreaseProductCountRequest
	(*IncreaseProductCountResponse)(nil),                          // 3: products.IncreaseProductCountResponse
	(*ReserveProductRequest)(nil),                                 // 4: products.ReserveProductRequest
	(*ReserveProductResponse)(nil),                                // 5: products.ReserveProductResponse
	(*ReleaseReservationRequest)(nil),                             // 6: products.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil),                            // 7: products.ReleaseReservationResponse
	(*ConfirmReservationRequest)(nil),                             // 8: products.ConfirmReservationRequest
	(*ConfirmReservationResponse)(nil),                            // 9: products.ConfirmReservationResponse
	(*IncreaseProductCountRequest_IncreaseProductCountBatch)(nil), // 10: products.IncreaseProductCountRequest.IncreaseProductCountBatch
	(*ReserveProductRequest_ProductCountBatch)(nil),               // 11: products.ReserveProductRequest.ProductCountBatch
	(*ReserveProductResponse_ReservationResult)(nil),              // 12: products.ReserveProductResponse.ReservationResult
}
var file_api_v1_products_proto_depIdxs = []int32{
	10, // 0: products.IncreaseProductCountRequest.products:type_name -> products.IncreaseProductCountRequest.IncreaseProductCountBatch
	11, // 1: products.ReserveProductRequest.products:type_name -> products.ReserveProductRequest.ProductCountBatch
	12, // 2: products.ReserveProductResponse.results:type_name -> products.ReserveProductResponse.ReservationResult
	0,  // 3: products.Products.GetProduct:input_type -> products.GetProductRequest
	2,  // 4: products.Products.IncreaseProductCount:input_type -> products.IncreaseProductCountRequest
	4,  // 5: products.Products.ReserveProduct:input_type -> products.ReserveProductRequest
	6,  // 6: products.Products.ReleaseReservation:input_type -> products.ReleaseReservationRequest
	8,  // 7: products.Products.ConfirmReservation:input_type -> products.ConfirmReservationRequest
	1,  // 8: products.Products.GetProduct:output_type -> products.GetProductResponse
	3,  // 9: products.Products.IncreaseProductCount:output_type -> products.IncreaseProductCountResponse
	5,  // 10: products.Products.ReserveProduct:output_type -> products.ReserveProductResponse
	7,  // 11: products.Products.ReleaseReservation:output_type -> products.ReleaseReservationResponse
	9,  // 12: products.Products.ConfirmReservation:output_type -> products.ConfirmReservationResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_products_proto_init() }
func file_api_v1_products_proto_init() {
	if File_api_v1_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_products_proto_rawDesc), len(file_api_v1_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_products_proto_goTypes,
		DependencyIndexes: file_api_v1_products_proto_depIdxs,
		MessageInfos:      file_api_v1_products_proto_msgTypes,
	}.Build()
	File_api_v1_products_proto = out.File
	file_api_v1_products_proto_goTypes = nil
	file_api_v1_products_proto_depIdxs = nil
}
