-- +goose Up
-- +goose StatementBegin
CREATE TABLE reservations(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku        BIGINT                                 NOT NULL REFERENCES products,
    count      INTEGER                                NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE reservations;
-- +goose StatementEnd
