// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/products.proto

package products

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_api_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductResponse) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *GetProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetProductResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type IncreaseStockRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Stocks        []*IncreaseStockRequest_IncreaseStockBatch `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockRequest) Reset() {
	*x = IncreaseStockRequest{}
	mi := &file_api_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockRequest) ProtoMessage() {}

func (x *IncreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockRequest.ProtoReflect.Descriptor instead.
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{2}
}

func (x *IncreaseStockRequest) GetStocks() []*IncreaseStockRequest_IncreaseStockBatch {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type IncreaseStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*IncreaseStockResponse_Success_
	//	*IncreaseStockResponse_Error_
	Result        isIncreaseStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockResponse) Reset() {
	*x = IncreaseStockResponse{}
	mi := &file_api_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockResponse) ProtoMessage() {}

func (x *IncreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockResponse.ProtoReflect.Descriptor instead.
func (*IncreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{3}
}

func (x *IncreaseStockResponse) GetResult() isIncreaseStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *IncreaseStockResponse) GetSuccess() *IncreaseStockResponse_Success {
	if x != nil {
		if x, ok := x.Result.(*IncreaseStockResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *IncreaseStockResponse) GetError() *IncreaseStockResponse_Error {
	if x != nil {
		if x, ok := x.Result.(*IncreaseStockResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isIncreaseStockResponse_Result interface {
	isIncreaseStockResponse_Result()
}

type IncreaseStockResponse_Success_ struct {
	Success *IncreaseStockResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type IncreaseStockResponse_Error_ struct {
	Error *IncreaseStockResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*IncreaseStockResponse_Success_) isIncreaseStockResponse_Result() {}

func (*IncreaseStockResponse_Error_) isIncreaseStockResponse_Result() {}

type DecreaseStockRequest struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Stocks        []*DecreaseStockRequest_IncreaseStockBatch `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockRequest) Reset() {
	*x = DecreaseStockRequest{}
	mi := &file_api_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockRequest) ProtoMessage() {}

func (x *DecreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockRequest.ProtoReflect.Descriptor instead.
func (*DecreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{4}
}

func (x *DecreaseStockRequest) GetStocks() []*DecreaseStockRequest_IncreaseStockBatch {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type DecreaseStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DecreaseStockResponse_Success_
	//	*DecreaseStockResponse_Error_
	Result        isDecreaseStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockResponse) Reset() {
	*x = DecreaseStockResponse{}
	mi := &file_api_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockResponse) ProtoMessage() {}

func (x *DecreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockResponse.ProtoReflect.Descriptor instead.
func (*DecreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{5}
}

func (x *DecreaseStockResponse) GetResult() isDecreaseStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DecreaseStockResponse) GetSuccess() *DecreaseStockResponse_Success {
	if x != nil {
		if x, ok := x.Result.(*DecreaseStockResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DecreaseStockResponse) GetError() *DecreaseStockResponse_Error {
	if x != nil {
		if x, ok := x.Result.(*DecreaseStockResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isDecreaseStockResponse_Result interface {
	isDecreaseStockResponse_Result()
}

type DecreaseStockResponse_Success_ struct {
	Success *DecreaseStockResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DecreaseStockResponse_Error_ struct {
	Error *DecreaseStockResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DecreaseStockResponse_Success_) isDecreaseStockResponse_Result() {}

func (*DecreaseStockResponse_Error_) isDecreaseStockResponse_Result() {}

type IncreaseStockRequest_IncreaseStockBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockRequest_IncreaseStockBatch) Reset() {
	*x = IncreaseStockRequest_IncreaseStockBatch{}
	mi := &file_api_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockRequest_IncreaseStockBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockRequest_IncreaseStockBatch) ProtoMessage() {}

func (x *IncreaseStockRequest_IncreaseStockBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockRequest_IncreaseStockBatch.ProtoReflect.Descriptor instead.
func (*IncreaseStockRequest_IncreaseStockBatch) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{2, 0}
}

func (x *IncreaseStockRequest_IncreaseStockBatch) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *IncreaseStockRequest_IncreaseStockBatch) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IncreaseStockResponse_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockResponse_Success) Reset() {
	*x = IncreaseStockResponse_Success{}
	mi := &file_api_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockResponse_Success) ProtoMessage() {}

func (x *IncreaseStockResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockResponse_Success.ProtoReflect.Descriptor instead.
func (*IncreaseStockResponse_Success) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{3, 0}
}

type IncreaseStockResponse_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockResponse_Error) Reset() {
	*x = IncreaseStockResponse_Error{}
	mi := &file_api_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockResponse_Error) ProtoMessage() {}

func (x *IncreaseStockResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockResponse_Error.ProtoReflect.Descriptor instead.
func (*IncreaseStockResponse_Error) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{3, 1}
}

func (x *IncreaseStockResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DecreaseStockRequest_IncreaseStockBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           uint64                 `protobuf:"varint,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockRequest_IncreaseStockBatch) Reset() {
	*x = DecreaseStockRequest_IncreaseStockBatch{}
	mi := &file_api_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockRequest_IncreaseStockBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockRequest_IncreaseStockBatch) ProtoMessage() {}

func (x *DecreaseStockRequest_IncreaseStockBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockRequest_IncreaseStockBatch.ProtoReflect.Descriptor instead.
func (*DecreaseStockRequest_IncreaseStockBatch) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DecreaseStockRequest_IncreaseStockBatch) GetSku() uint64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *DecreaseStockRequest_IncreaseStockBatch) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DecreaseStockResponse_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockResponse_Success) Reset() {
	*x = DecreaseStockResponse_Success{}
	mi := &file_api_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockResponse_Success) ProtoMessage() {}

func (x *DecreaseStockResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockResponse_Success.ProtoReflect.Descriptor instead.
func (*DecreaseStockResponse_Success) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{5, 0}
}

type DecreaseStockResponse_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockResponse_Error) Reset() {
	*x = DecreaseStockResponse_Error{}
	mi := &file_api_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockResponse_Error) ProtoMessage() {}

func (x *DecreaseStockResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockResponse_Error.ProtoReflect.Descriptor instead.
func (*DecreaseStockResponse_Error) Descriptor() ([]byte, []int) {
	return file_api_products_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DecreaseStockResponse_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_products_proto protoreflect.FileDescriptor

const file_api_products_proto_rawDesc = "" +
	"\n" +
	"\x12api/products.proto\x12\bproducts\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"%\n" +
	"\x11GetProductRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\"f\n" +
	"\x12GetProductResponse\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\"\x9f\x01\n" +
	"\x14IncreaseStockRequest\x12I\n" +
	"\x06stocks\x18\x01 \x03(\v21.products.IncreaseStockRequest.IncreaseStockBatchR\x06stocks\x1a<\n" +
	"\x12IncreaseStockBatch\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xd3\x01\n" +
	"\x15IncreaseStockResponse\x12C\n" +
	"\asuccess\x18\x01 \x01(\v2'.products.IncreaseStockResponse.SuccessH\x00R\asuccess\x12=\n" +
	"\x05error\x18\x02 \x01(\v2%.products.IncreaseStockResponse.ErrorH\x00R\x05error\x1a\t\n" +
	"\aSuccess\x1a!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\b\n" +
	"\x06result\"\x9f\x01\n" +
	"\x14DecreaseStockRequest\x12I\n" +
	"\x06stocks\x18\x01 \x03(\v21.products.DecreaseStockRequest.IncreaseStockBatchR\x06stocks\x1a<\n" +
	"\x12IncreaseStockBatch\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\x04R\x03sku\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xd3\x01\n" +
	"\x15DecreaseStockResponse\x12C\n" +
	"\asuccess\x18\x01 \x01(\v2'.products.DecreaseStockResponse.SuccessH\x00R\asuccess\x12=\n" +
	"\x05error\x18\x02 \x01(\v2%.products.DecreaseStockResponse.ErrorH\x00R\x05error\x1a\t\n" +
	"\aSuccess\x1a!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\b\n" +
	"\x06result2\xab\x03\n" +
	"\x0fProductsService\x12\xa3\x01\n" +
	"\n" +
	"GetProduct\x12\x1b.products.GetProductRequest\x1a\x1c.products.GetProductResponse\"Z\x92A=\x1a;Получение информации о продукте\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/products/{sku}\x12x\n" +
	"\rIncreaseStock\x12\x1e.products.IncreaseStockRequest\x1a\x1f.products.IncreaseStockResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/products/increase-stock\x12x\n" +
	"\rDecreaseStock\x12\x1e.products.DecreaseStockRequest\x1a\x1f.products.DecreaseStockResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/products/decrease-stockB/Z-ozon-simulator-go-products/api/proto;productsb\x06proto3"

var (
	file_api_products_proto_rawDescOnce sync.Once
	file_api_products_proto_rawDescData []byte
)

func file_api_products_proto_rawDescGZIP() []byte {
	file_api_products_proto_rawDescOnce.Do(func() {
		file_api_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_products_proto_rawDesc), len(file_api_products_proto_rawDesc)))
	})
	return file_api_products_proto_rawDescData
}

var file_api_products_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_products_proto_goTypes = []any{
	(*GetProductRequest)(nil),                       // 0: products.GetProductRequest
	(*GetProductResponse)(nil),                      // 1: products.GetProductResponse
	(*IncreaseStockRequest)(nil),                    // 2: products.IncreaseStockRequest
	(*IncreaseStockResponse)(nil),                   // 3: products.IncreaseStockResponse
	(*DecreaseStockRequest)(nil),                    // 4: products.DecreaseStockRequest
	(*DecreaseStockResponse)(nil),                   // 5: products.DecreaseStockResponse
	(*IncreaseStockRequest_IncreaseStockBatch)(nil), // 6: products.IncreaseStockRequest.IncreaseStockBatch
	(*IncreaseStockResponse_Success)(nil),           // 7: products.IncreaseStockResponse.Success
	(*IncreaseStockResponse_Error)(nil),             // 8: products.IncreaseStockResponse.Error
	(*DecreaseStockRequest_IncreaseStockBatch)(nil), // 9: products.DecreaseStockRequest.IncreaseStockBatch
	(*DecreaseStockResponse_Success)(nil),           // 10: products.DecreaseStockResponse.Success
	(*DecreaseStockResponse_Error)(nil),             // 11: products.DecreaseStockResponse.Error
}
var file_api_products_proto_depIdxs = []int32{
	6,  // 0: products.IncreaseStockRequest.stocks:type_name -> products.IncreaseStockRequest.IncreaseStockBatch
	7,  // 1: products.IncreaseStockResponse.success:type_name -> products.IncreaseStockResponse.Success
	8,  // 2: products.IncreaseStockResponse.error:type_name -> products.IncreaseStockResponse.Error
	9,  // 3: products.DecreaseStockRequest.stocks:type_name -> products.DecreaseStockRequest.IncreaseStockBatch
	10, // 4: products.DecreaseStockResponse.success:type_name -> products.DecreaseStockResponse.Success
	11, // 5: products.DecreaseStockResponse.error:type_name -> products.DecreaseStockResponse.Error
	0,  // 6: products.ProductsService.GetProduct:input_type -> products.GetProductRequest
	2,  // 7: products.ProductsService.IncreaseStock:input_type -> products.IncreaseStockRequest
	4,  // 8: products.ProductsService.DecreaseStock:input_type -> products.DecreaseStockRequest
	1,  // 9: products.ProductsService.GetProduct:output_type -> products.GetProductResponse
	3,  // 10: products.ProductsService.IncreaseStock:output_type -> products.IncreaseStockResponse
	5,  // 11: products.ProductsService.DecreaseStock:output_type -> products.DecreaseStockResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_products_proto_init() }
func file_api_products_proto_init() {
	if File_api_products_proto != nil {
		return
	}
	file_api_products_proto_msgTypes[3].OneofWrappers = []any{
		(*IncreaseStockResponse_Success_)(nil),
		(*IncreaseStockResponse_Error_)(nil),
	}
	file_api_products_proto_msgTypes[5].OneofWrappers = []any{
		(*DecreaseStockResponse_Success_)(nil),
		(*DecreaseStockResponse_Error_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_products_proto_rawDesc), len(file_api_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_products_proto_goTypes,
		DependencyIndexes: file_api_products_proto_depIdxs,
		MessageInfos:      file_api_products_proto_msgTypes,
	}.Build()
	File_api_products_proto = out.File
	file_api_products_proto_goTypes = nil
	file_api_products_proto_depIdxs = nil
}
