http-server:
  host:
  port: 8080

grpc-server:
  host: localhost
  port: 8082

database:
  user: postgres
  password: 1234
  host: localhost
  port: 5432
  name: ozon_simulator_go_products

authorization:
  enabled: false
  admin-user: 'admin'

logging:
  log-request-body: true
  log-response-body: true

kafka:
  brokers:
    - localhost:9092
  product-events-topic: product.events

jobs:
  reservation-expiry:
    enabled: true
    ttl: 30m
    job-interval: 10m
  product-events-outbox:
    enabled: true
    job-interval: 10s
    batch-size: 100
    max-retries: 5
