http-server:
  host:
  port: 8081

grpc-server:
  host: localhost
  port: 50051

database:
  user: postgres
  password: 1234
  host: localhost
  port: 5432
  name: ozon_simulator_go_products

authorization:
  enabled: false
  admin-user: 'admin'