http-server:
  host:
  port: 8080

grpc-server:
  host: localhost
  port: 8082

database:
  user: postgres
  password: 1234
  host: localhost
  port: 5432
  name: marketplace_simulator_product

authorization:
  enabled: false
  admin-user: 'admin'

logging:
  log-request-body: true
  log-response-body: true

tracing:
  enabled: true
  otlp-endpoint: localhost:4317

kafka:
  brokers:
    - localhost:9092
  product-events-topic: product.events
  write-timeout: 5s

jobs:
  reservation-expiry:
    enabled: true
    ttl: 5m
    job-interval: 1s
  product-events-outbox:
    enabled: true
    job-interval: 1s
    batch-size: 100
    max-retries: 5
  product-events-outbox-monitor:
    enabled: true
    job-interval: 10s
